config:
  research-analysis-infra:environment: dev
  research-analysis-infra:location: uksouth
secretsprovider: azurekeyvault://rap-kv-18c845ca.vault.azure.net/keys/pulumi-state-secrets
encryptedkey: Z296RFYxOGhVRmhBSGwyeFFtVUlFUjYwQU9oOGl2VW0wUklhd1VmNDlfZXBtbGd6VjEtdkNQLWpFQXh1LVBCMU8tRE1seTVia3VaX0EwbmFSVmpPLXBVb094RU5EdDBYM0NaN3lqSk1tLUtHNk5NcHNYb19jUmtEV2xPbmc5STN0MENmSk5HbEZzTEdsOUZWdWtwLVJoS0p2WFdaMy1hTGpVS3NXcklwV3JYZjl3YUxxSVdWTFcySTE0Z19CQng0bzhhQTNkNXF0ZGd3OHpWaFpnRWNmNGFpYTZzWE5fSjE2bHdNc3RWZWJLcGs1cWtaNDBPa2ZxTDNZWmtLVjE5UFVJeC14SFZDajRwR0Nrak05V3B4dXlTbHh0Y0VFb1NsSFN1THNNb2Fac3BVUEZReGlmSF9pdmF1UWFmcDRITGNmTk1yVzktdU4xcTZ4R1kwcDdoV25B
